FROM python:3.10.6-slim-buster

RUN apt-get update
RUN apt-get install -y nano socat
RUN pip install secp256k1
RUN pip install cryptography

WORKDIR /opt
COPY ./src .

CMD socat TCP-LISTEN:5000,fork,reuseaddr EXEC:'python -u ./chall.py'