# Use an official Ubuntu 22.04 base image
FROM ubuntu:22.04

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y \
    nano \
    socat \
    build-essential \
    m4 \
    gcc \
    gfortran \
    perl \
    git \
    texinfo \
    wget \
    dpkg-dev \
    xz-utils \
    python3 \
    python3-pip \
    python3-dev \
    libffi-dev \
    libssl-dev \
    libzmq3-dev \
    libcurl4-openssl-dev \
    libtool \
    libboost-all-dev \
    libgmp-dev \
    libmpfr-dev \
    libmpc-dev \
    libssl-dev \
    libsqlite3-dev \
    libbz2-dev \
    libreadline-dev \
    libncurses5-dev \
    libncursesw5-dev \
    tk-dev \
    liblzma-dev \
    zlib1g-dev \
    libopenblas-dev \
    liblapack-dev \
    && apt-get clean

# Download and install SageMath 9.5
RUN wget -O /tmp/sage-9.5.tar.gz https://github.com/sagemath/sage/archive/refs/tags/9.5.tar.gz && \
    mkdir /opt/sage && \
    tar -xvzf /tmp/sage-9.5.tar.gz -C /opt/sage --strip-components=1 && \
    rm /tmp/sage-9.5.tar.gz

# Navigate to the directory containing the configure script
WORKDIR /opt/sage

RUN make configure
RUN ./configure

# Build SageMath from source
RUN make -j$(nproc)

# Install Python dependencies
RUN pip install --no-cache-dir pycryptodome

WORKDIR /opt
COPY ./src .

CMD socat TCP-LISTEN:5000,fork,reuseaddr EXEC:'python -u ./chall.py'