# Base image
FROM ubuntu:22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Update and install dependencies
RUN apt update && apt install -y \
    build-essential \
    python3-pip \
    python3-dev \
    curl \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install SageMath 9.5
RUN apt install -y sagemath

# check version
RUN sage --version

RUN apt install -y nano socat
RUN pip install pycryptodome

WORKDIR /opt
COPY ./src .

CMD socat TCP-LISTEN:5000,fork,reuseaddr EXEC:'python -u ./chall.py'